#!/usr/bin/env python3
"""
pdf_text_replace.py
-------------------
对 PDF 文字段进行背景覆盖与内容重写。

依赖:
    - PyMuPDF (fitz)
    - Pillow
    - PyYAML

Author: Generated by ChatGPT
"""
import argparse
import io, math, logging, sys
from collections import Counter
from itertools import combinations
from pathlib import Path
import re
from typing import Optional

import fitz  # PyMuPDF
from PIL import Image, ImageColor, ImageStat
import yaml

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)


def load_config(path: Optional[Path]):
    default_cfg = {
        "font_family": "auto",
        "font_size": None,
        "fill_color": "#333333",
        "dpi": 300,
        "merge_threshold_pt": 1.5,
        "background_sample_ring": 3,
        "background_histogram_step": 8,
        "foreground_tolerance": 24,
        "tight_box_padding_px": 1,
        "char_box_margin_px": 1,
        "thin_component_thickness_px": 4,
        "thin_component_span_ratio": 0.6,
        "min_foreground_component_px": 4,
        "line_boundary_search_px": 40,
        "line_boundary_margin_px": 0,
        "char_probe_shrink_ratio": 0.25,
        "page_line_axis_tolerance_pt": 0.25,
        "page_line_merge_tolerance_pt": 1.0,
        "page_line_min_span_pt": 8,
        "page_line_safety_px": 1,
        "_config_dir": path.parent.resolve() if path else Path.cwd(),
        "_warned_fonts": set(),
    }
    if path and path.exists():
        with open(path, "r", encoding="utf-8") as f:
            user_cfg = yaml.safe_load(f) or {}
        default_cfg.update(user_cfg)
    return default_cfg


def parse_fill_color(value):
    """Convert a CSS-style RGB value into the float tuple PyMuPDF expects."""
    if isinstance(value, (list, tuple)) and len(value) == 3:
        channels = [float(channel) for channel in value]
        if all(0 <= channel <= 1 for channel in channels):
            return tuple(channels)
        if all(0 <= channel <= 255 for channel in channels):
            return tuple(channel / 255 for channel in channels)
        raise ValueError(f"Unsupported RGB channel range: {value!r}")

    rgb = ImageColor.getrgb(str(value))
    return tuple(channel / 255 for channel in rgb)


def rotation_from_line(line):
    """Map PyMuPDF's line direction vector to insert_textbox's rotation enum."""
    direction = line.get("dir") or (1.0, 0.0)
    dx, dy = direction
    raw_angle = math.degrees(math.atan2(-dy, dx)) % 360
    supported = (0, 90, 180, 270)
    rotation = min(supported, key=lambda angle: abs(angle - raw_angle))
    if abs(rotation - raw_angle) > 1:
        logging.warning(
            "Unsupported text direction %s; snapped %.2f degrees to %d",
            direction,
            raw_angle,
            rotation,
        )
    return rotation


def fallback_font_for_text(text):
    return "china-s" if any(ord(char) > 127 for char in text) else "helv"


def resolve_font(face_name, cfg, text):
    font_family = str(cfg["font_family"]).strip()
    if font_family.lower() in {"", "auto", "original"}:
        if face_name:
            try:
                fitz.Font(fontname=face_name)
                return face_name, None
            except Exception:
                pass
        return fallback_font_for_text(text), None

    for candidate in (
        Path(font_family),
        Path(cfg["_config_dir"]) / font_family,
    ):
        if candidate.is_file():
            resolved = str(candidate.resolve())
            alias = f"userfont_{abs(hash(resolved))}"
            return alias, resolved

    try:
        fitz.Font(fontname=font_family)
        return font_family, None
    except Exception:
        fallback = fallback_font_for_text(text)
        warning_key = (font_family, fallback)
        if warning_key not in cfg["_warned_fonts"]:
            logging.warning(
                "Font '%s' is unavailable; falling back to '%s'. "
                "Use a PyMuPDF built-in font name or a TTF/OTF file path.",
                font_family,
                fallback,
            )
            cfg["_warned_fonts"].add(warning_key)
        return fallback, None


class TextBox:
    __slots__ = ("text", "bbox", "font", "size", "rotation", "origin", "char_bboxes")

    def __init__(self, text, bbox, font, size, rotation, origin, char_bboxes):
        self.text = text
        self.bbox = bbox  # (x0, y0, x1, y1) in pt
        self.font = font
        self.size = size
        self.rotation = rotation
        self.origin = origin
        self.char_bboxes = char_bboxes

    def mergeable(self, other, threshold_pt):
        # 简单按中心点距离判断
        cx1 = (self.bbox[0] + self.bbox[2]) / 2
        cy1 = (self.bbox[1] + self.bbox[3]) / 2
        cx2 = (other.bbox[0] + other.bbox[2]) / 2
        cy2 = (other.bbox[1] + other.bbox[3]) / 2
        dist = math.hypot(cx1 - cx2, cy1 - cy2)
        return dist <= threshold_pt and abs(self.rotation - other.rotation) < 1e-2


def extract_textboxes(page, cfg):
    """按行/段合并文字 span，返回 TextBox 列表"""
    text_dict = page.get_text("rawdict")  # blocks -> lines -> spans -> chars
    threshold = cfg["merge_threshold_pt"]
    boxes = []

    for block in text_dict["blocks"]:
        if block["type"] != 0:
            continue
        for line in block["lines"]:
            line_rotation = rotation_from_line(line)
            current_tb = None
            for span in line["spans"]:
                chars = span.get("chars", [])
                text = "".join(char.get("c", "") for char in chars)
                if not text:
                    continue
                bbox = span["bbox"]
                tb = TextBox(
                    text,
                    bbox,
                    span["font"],
                    span["size"],
                    line_rotation,
                    span["origin"],
                    [
                        char["bbox"]
                        for char in chars
                        if char.get("c", "") and not char.get("c", "").isspace()
                    ],
                )
                if current_tb and current_tb.mergeable(tb, threshold):
                    # merge
                    current_tb.text += tb.text
                    current_tb.char_bboxes.extend(tb.char_bboxes)
                    x0, y0, x1, y1 = current_tb.bbox
                    x0 = min(x0, bbox[0])
                    y0 = min(y0, bbox[1])
                    x1 = max(x1, bbox[2])
                    y1 = max(y1, bbox[3])
                    current_tb.bbox = (x0, y0, x1, y1)
                else:
                    if current_tb:
                        boxes.append(current_tb)
                    current_tb = tb
            if current_tb:
                boxes.append(current_tb)
                current_tb = None
    return boxes


def pt_box_to_px_bounds(box_pt, dpi, img):
    x0 = max(int(math.floor(box_pt[0] / 72 * dpi)), 0)
    y0 = max(int(math.floor(box_pt[1] / 72 * dpi)), 0)
    x1 = min(int(math.ceil(box_pt[2] / 72 * dpi)), img.width)
    y1 = min(int(math.ceil(box_pt[3] / 72 * dpi)), img.height)
    return (x0, y0, max(x1, x0 + 1), max(y1, y0 + 1))


def pt_boxes_to_px_bounds(boxes_pt, dpi, img):
    return [pt_box_to_px_bounds(box_pt, dpi, img) for box_pt in boxes_pt]


def px_bounds_to_pt_rect(bounds_px, dpi):
    x0, y0, x1, y1 = bounds_px
    scale = 72 / dpi
    return fitz.Rect(x0 * scale, y0 * scale, x1 * scale, y1 * scale)


def pt_to_px(value_pt, dpi):
    return value_pt / 72 * dpi


def shrink_box(box, ratio):
    x0, y0, x1, y1 = box
    if not 0 < ratio < 0.5:
        return box
    dx = (x1 - x0) * ratio
    dy = (y1 - y0) * ratio
    return (x0 + dx, y0 + dy, x1 - dx, y1 - dy)


def union_bounds(boxes):
    if not boxes:
        return None
    return (
        min(box[0] for box in boxes),
        min(box[1] for box in boxes),
        max(box[2] for box in boxes),
        max(box[3] for box in boxes),
    )


def text_probe_bounds(tb: TextBox, cfg):
    if not tb.char_bboxes:
        return tb.bbox
    ratio = float(cfg["char_probe_shrink_ratio"])
    boxes = [shrink_box(box, ratio) for box in tb.char_bboxes]
    probe = union_bounds(boxes)
    return probe or tb.bbox


def text_reference_point(tb: TextBox, cfg):
    x0, y0, x1, y1 = text_probe_bounds(tb, cfg)
    return ((x0 + x1) / 2, (y0 + y1) / 2)


def boundary_pt_to_safe_px(value_pt, side, cfg):
    raw_px = pt_to_px(value_pt, cfg["dpi"])
    safety = max(int(cfg["page_line_safety_px"]), 0)
    if side in {"left", "top"}:
        return math.ceil(raw_px) + safety
    return math.floor(raw_px) - safety


PDF_TEXT_BLOCK_RE = re.compile(rb"BT(?P<body>.*?)ET", re.DOTALL)
PDF_LITERAL_STRING_RE = re.compile(rb"\((?:\\.|[^\\)])*\)")


def decode_pdf_literal_string(token):
    content = token[1:-1]
    out = bytearray()
    i = 0
    while i < len(content):
        byte = content[i]
        if byte != 0x5C:  # backslash
            out.append(byte)
            i += 1
            continue

        i += 1
        if i >= len(content):
            break
        esc = content[i]
        if esc in b"nrtbf":
            mapping = {
                ord("n"): b"\n",
                ord("r"): b"\r",
                ord("t"): b"\t",
                ord("b"): b"\b",
                ord("f"): b"\f",
            }
            out.extend(mapping[esc])
            i += 1
            continue
        if esc in b"()\\":
            out.append(esc)
            i += 1
            continue
        if esc in b"\r\n":
            if esc == ord("\r") and i + 1 < len(content) and content[i + 1] == ord("\n"):
                i += 2
            else:
                i += 1
            continue
        if 48 <= esc <= 55:
            digits = [esc]
            i += 1
            while i < len(content) and len(digits) < 3 and 48 <= content[i] <= 55:
                digits.append(content[i])
                i += 1
            out.append(int(bytes(digits), 8))
            continue

        out.append(esc)
        i += 1

    return bytes(out)


def whitespace_only_type3_text_block(body, type3_resource_names):
    if not type3_resource_names:
        return False

    if not any(f"/{name}".encode() in body for name in type3_resource_names):
        return False

    strings = [decode_pdf_literal_string(token) for token in PDF_LITERAL_STRING_RE.findall(body)]
    if not strings:
        return False

    return all(not decoded.strip() for decoded in strings)


def strip_whitespace_only_type3_blocks(doc, page):
    type3_resource_names = {
        font[4]
        for font in page.get_fonts(full=True)
        if str(font[2]).lower() == "type3"
    }
    if not type3_resource_names:
        return 0

    removed = 0
    for xref in page.get_contents():
        stream = doc.xref_stream(xref)
        if not stream:
            continue

        def replacer(match):
            nonlocal removed
            body = match.group("body")
            if whitespace_only_type3_text_block(body, type3_resource_names):
                removed += 1
                return b"\n"
            return match.group(0)

        updated = PDF_TEXT_BLOCK_RE.sub(replacer, stream)
        if updated != stream:
            doc.update_stream(xref, updated)

    return removed


def surrounding_regions(inner_bounds, ring, img):
    inner_x0, inner_y0, inner_x1, inner_y1 = inner_bounds
    outer_x0 = max(inner_x0 - ring, 0)
    outer_y0 = max(inner_y0 - ring, 0)
    outer_x1 = min(inner_x1 + ring, img.width)
    outer_y1 = min(inner_y1 + ring, img.height)
    return [
        (outer_x0, outer_y0, outer_x1, inner_y0),  # top
        (outer_x0, inner_y1, outer_x1, outer_y1),  # bottom
        (outer_x0, inner_y0, inner_x0, inner_y1),  # left
        (inner_x1, inner_y0, outer_x1, inner_y1),  # right
    ]


def dominant_background_color(img: Image.Image, box_pt, cfg):
    dpi = cfg["dpi"]
    ring = cfg["background_sample_ring"]
    step = max(int(cfg["background_histogram_step"]), 1)
    inner_bounds = pt_box_to_px_bounds(box_pt, dpi, img)
    regions = surrounding_regions(inner_bounds, ring, img)

    buckets = Counter()
    bucket_sums = {}
    bucket_counts = Counter()
    for x0, y0, x1, y1 in regions:
        if x1 <= x0 or y1 <= y0:
            continue
        crop = img.crop((x0, y0, x1, y1))
        for pixel in crop.getdata():
            bucket = tuple(channel // step for channel in pixel[:3])
            buckets[bucket] += 1
            bucket_counts[bucket] += 1
            if bucket not in bucket_sums:
                bucket_sums[bucket] = [0, 0, 0]
            for i in range(3):
                bucket_sums[bucket][i] += pixel[i]

    if not buckets:
        crop = img.crop(inner_bounds)
        r, g, b = [int(c) for c in ImageStat.Stat(crop).mean[:3]]
        rgb255 = (r, g, b)
        return tuple(channel / 255 for channel in rgb255), rgb255

    bucket, _ = buckets.most_common(1)[0]
    rgb255 = tuple(
        int(round(bucket_sums[bucket][i] / bucket_counts[bucket])) for i in range(3)
    )
    return tuple(channel / 255 for channel in rgb255), rgb255


def color_distance_sq(rgb_a, rgb_b):
    return sum((int(a) - int(b)) ** 2 for a, b in zip(rgb_a[:3], rgb_b[:3]))


def foreground_components(img: Image.Image, bounds_px, bg_rgb255, cfg):
    x0, y0, x1, y1 = bounds_px
    crop = img.crop(bounds_px)
    width, height = crop.size
    if width <= 0 or height <= 0:
        return []

    tolerance_sq = int(cfg["foreground_tolerance"]) ** 2
    pixels = [pixel[:3] for pixel in crop.getdata()]
    mask = [
        color_distance_sq(pixel, bg_rgb255) > tolerance_sq for pixel in pixels
    ]

    components = []
    visited = [False] * len(mask)
    offsets = (
        (-1, -1),
        (0, -1),
        (1, -1),
        (-1, 0),
        (1, 0),
        (-1, 1),
        (0, 1),
        (1, 1),
    )

    for index, is_foreground in enumerate(mask):
        if not is_foreground or visited[index]:
            continue

        stack = [index]
        visited[index] = True
        area = 0
        min_x = max_x = index % width
        min_y = max_y = index // width

        while stack:
            current = stack.pop()
            cx = current % width
            cy = current // width
            area += 1
            min_x = min(min_x, cx)
            max_x = max(max_x, cx)
            min_y = min(min_y, cy)
            max_y = max(max_y, cy)

            for dx, dy in offsets:
                nx = cx + dx
                ny = cy + dy
                if nx < 0 or nx >= width or ny < 0 or ny >= height:
                    continue
                neighbor = ny * width + nx
                if visited[neighbor] or not mask[neighbor]:
                    continue
                visited[neighbor] = True
                stack.append(neighbor)

        components.append(
            {
                "x0": x0 + min_x,
                "y0": y0 + min_y,
                "x1": x0 + max_x + 1,
                "y1": y0 + max_y + 1,
                "width": max_x - min_x + 1,
                "height": max_y - min_y + 1,
                "area": area,
            }
        )

    return components


def is_horizontal_line(component, ref_width, cfg):
    thickness = max(int(cfg["thin_component_thickness_px"]), 1)
    span_ratio = float(cfg["thin_component_span_ratio"])
    return (
        component["height"] <= thickness
        and component["width"] >= max(8, int(ref_width * span_ratio))
    )


def is_vertical_line(component, ref_height, cfg):
    thickness = max(int(cfg["thin_component_thickness_px"]), 1)
    span_ratio = float(cfg["thin_component_span_ratio"])
    return (
        component["width"] <= thickness
        and component["height"] >= max(8, int(ref_height * span_ratio))
    )


def merge_axis_lines(lines, orientation, cfg):
    if not lines:
        return []

    tolerance = float(cfg["page_line_merge_tolerance_pt"])
    merged = []
    sort_key = (
        (lambda line: (line["pos_pt"], line["start_pt"], line["end_pt"]))
        if orientation == "h"
        else (lambda line: (line["pos_pt"], line["start_pt"], line["end_pt"]))
    )

    for line in sorted(lines, key=sort_key):
        target = None
        for current in merged:
            if abs(current["pos_pt"] - line["pos_pt"]) > tolerance:
                continue
            if (
                line["start_pt"] > current["end_pt"] + tolerance
                or current["start_pt"] > line["end_pt"] + tolerance
            ):
                continue
            target = current
            break

        if target is None:
            merged.append({**line, "_count": 1})
            continue

        count = target["_count"] + 1
        target["pos_pt"] = (
            target["pos_pt"] * target["_count"] + line["pos_pt"]
        ) / count
        target["start_pt"] = min(target["start_pt"], line["start_pt"])
        target["end_pt"] = max(target["end_pt"], line["end_pt"])
        target["half_thickness_pt"] = max(
            target["half_thickness_pt"], line["half_thickness_pt"]
        )
        target["_count"] = count

    for line in merged:
        line.pop("_count", None)
    return merged


def extract_page_vector_lines(page, cfg):
    axis_tolerance = float(cfg["page_line_axis_tolerance_pt"])
    min_span = float(cfg["page_line_min_span_pt"])
    horizontal = []
    vertical = []

    for drawing in page.get_drawings():
        if drawing.get("type") not in {"s", "fs"}:
            continue

        half_thickness_pt = max(float(drawing.get("width") or 0.0) / 2, 0.25)
        for item in drawing.get("items", []):
            kind = item[0]
            if kind == "l":
                p0, p1 = item[1], item[2]
                if abs(p0.y - p1.y) <= axis_tolerance and abs(p0.x - p1.x) >= min_span:
                    horizontal.append(
                        {
                            "pos_pt": (p0.y + p1.y) / 2,
                            "start_pt": min(p0.x, p1.x),
                            "end_pt": max(p0.x, p1.x),
                            "half_thickness_pt": half_thickness_pt,
                        }
                    )
                elif abs(p0.x - p1.x) <= axis_tolerance and abs(p0.y - p1.y) >= min_span:
                    vertical.append(
                        {
                            "pos_pt": (p0.x + p1.x) / 2,
                            "start_pt": min(p0.y, p1.y),
                            "end_pt": max(p0.y, p1.y),
                            "half_thickness_pt": half_thickness_pt,
                        }
                    )
            elif kind == "re":
                rect = item[1]
                if rect.width >= min_span:
                    horizontal.append(
                        {
                            "pos_pt": rect.y0,
                            "start_pt": rect.x0,
                            "end_pt": rect.x1,
                            "half_thickness_pt": half_thickness_pt,
                        }
                    )
                    horizontal.append(
                        {
                            "pos_pt": rect.y1,
                            "start_pt": rect.x0,
                            "end_pt": rect.x1,
                            "half_thickness_pt": half_thickness_pt,
                        }
                    )
                if rect.height >= min_span:
                    vertical.append(
                        {
                            "pos_pt": rect.x0,
                            "start_pt": rect.y0,
                            "end_pt": rect.y1,
                            "half_thickness_pt": half_thickness_pt,
                        }
                    )
                    vertical.append(
                        {
                            "pos_pt": rect.x1,
                            "start_pt": rect.y0,
                            "end_pt": rect.y1,
                            "half_thickness_pt": half_thickness_pt,
                        }
                    )

    return {
        "horizontal": merge_axis_lines(horizontal, "h", cfg),
        "vertical": merge_axis_lines(vertical, "v", cfg),
    }


def line_covers_span(line, start_pt, end_pt, tolerance):
    return line["start_pt"] <= start_pt + tolerance and line["end_pt"] >= end_pt - tolerance


def frame_from_lines(left, right, top, bottom):
    return {
        "left_outer_pt": left["pos_pt"] - left["half_thickness_pt"],
        "left_inner_pt": left["pos_pt"] + left["half_thickness_pt"],
        "right_inner_pt": right["pos_pt"] - right["half_thickness_pt"],
        "right_outer_pt": right["pos_pt"] + right["half_thickness_pt"],
        "top_outer_pt": top["pos_pt"] - top["half_thickness_pt"],
        "top_inner_pt": top["pos_pt"] + top["half_thickness_pt"],
        "bottom_inner_pt": bottom["pos_pt"] - bottom["half_thickness_pt"],
        "bottom_outer_pt": bottom["pos_pt"] + bottom["half_thickness_pt"],
    }


def find_frames_from_vector_lines(page_lines, cfg):
    tolerance = float(cfg["page_line_merge_tolerance_pt"])
    min_span = float(cfg["page_line_min_span_pt"])
    frames = []
    seen = set()
    horizontal = page_lines["horizontal"]
    vertical = page_lines["vertical"]

    for left, right in combinations(vertical, 2):
        if right["pos_pt"] - left["pos_pt"] < min_span:
            continue
        for top, bottom in combinations(horizontal, 2):
            if bottom["pos_pt"] - top["pos_pt"] < min_span:
                continue
            if not line_covers_span(top, left["pos_pt"], right["pos_pt"], tolerance):
                continue
            if not line_covers_span(bottom, left["pos_pt"], right["pos_pt"], tolerance):
                continue
            if not line_covers_span(left, top["pos_pt"], bottom["pos_pt"], tolerance):
                continue
            if not line_covers_span(right, top["pos_pt"], bottom["pos_pt"], tolerance):
                continue

            frame = frame_from_lines(left, right, top, bottom)
            if (
                frame["right_inner_pt"] <= frame["left_inner_pt"]
                or frame["bottom_inner_pt"] <= frame["top_inner_pt"]
            ):
                continue

            key = tuple(round(value / tolerance) for value in frame.values())
            if key in seen:
                continue
            seen.add(key)
            frames.append(frame)

    return frames


def smallest_enclosing_frame(tb: TextBox, frames, cfg):
    probe = text_probe_bounds(tb, cfg)
    containing = [
        frame
        for frame in frames
        if frame["left_inner_pt"] <= probe[0]
        and frame["top_inner_pt"] <= probe[1]
        and frame["right_inner_pt"] >= probe[2]
        and frame["bottom_inner_pt"] >= probe[3]
    ]
    if not containing:
        return None
    containing.sort(
        key=lambda frame: (frame["right_inner_pt"] - frame["left_inner_pt"])
        * (frame["bottom_inner_pt"] - frame["top_inner_pt"])
    )
    return containing[0]


def page_boundaries_for_text(tb: TextBox, page_geometry, cfg):
    boundaries = {
        "left": None,
        "right": None,
        "top": None,
        "bottom": None,
        "margin": 0,
    }
    if not page_geometry:
        return boundaries

    probe = text_probe_bounds(tb, cfg)
    page_lines = page_geometry.get("lines", {})
    frames = page_geometry.get("frames", [])

    frame = smallest_enclosing_frame(tb, frames, cfg)
    if frame is not None:
        boundaries["left"] = boundary_pt_to_safe_px(frame["left_inner_pt"], "left", cfg)
        boundaries["right"] = boundary_pt_to_safe_px(
            frame["right_inner_pt"], "right", cfg
        )
        boundaries["top"] = boundary_pt_to_safe_px(frame["top_inner_pt"], "top", cfg)
        boundaries["bottom"] = boundary_pt_to_safe_px(
            frame["bottom_inner_pt"], "bottom", cfg
        )

    for line in page_lines.get("horizontal", []):
        if overlap_len(probe[0], probe[2], line["start_pt"], line["end_pt"]) <= 0:
            continue
        outer_top = line["pos_pt"] - line["half_thickness_pt"]
        outer_bottom = line["pos_pt"] + line["half_thickness_pt"]
        if outer_top >= probe[3]:
            candidate = boundary_pt_to_safe_px(outer_top, "bottom", cfg)
            boundaries["bottom"] = (
                candidate
                if boundaries["bottom"] is None
                else min(boundaries["bottom"], candidate)
            )
        elif outer_bottom <= probe[1]:
            candidate = boundary_pt_to_safe_px(outer_bottom, "top", cfg)
            boundaries["top"] = (
                candidate
                if boundaries["top"] is None
                else max(boundaries["top"], candidate)
            )

    for line in page_lines.get("vertical", []):
        if overlap_len(probe[1], probe[3], line["start_pt"], line["end_pt"]) <= 0:
            continue
        outer_left = line["pos_pt"] - line["half_thickness_pt"]
        outer_right = line["pos_pt"] + line["half_thickness_pt"]
        if outer_left >= probe[2]:
            candidate = boundary_pt_to_safe_px(outer_left, "right", cfg)
            boundaries["right"] = (
                candidate
                if boundaries["right"] is None
                else min(boundaries["right"], candidate)
            )
        elif outer_right <= probe[0]:
            candidate = boundary_pt_to_safe_px(outer_right, "left", cfg)
            boundaries["left"] = (
                candidate
                if boundaries["left"] is None
                else max(boundaries["left"], candidate)
            )

    return boundaries


def frame_inner_edges(component, text_bounds, cfg):
    width = max(component["width"], 1)
    height = max(component["height"], 1)
    fill_ratio = component["area"] / (width * height)
    perimeter = max(2 * (width + height) - 4, 1)
    estimated_thickness = max(
        1, int(round(component["area"] / perimeter))
    )

    encloses_text = (
        component["x0"] < text_bounds[0]
        and component["x1"] > text_bounds[2]
        and component["y0"] < text_bounds[1]
        and component["y1"] > text_bounds[3]
    )
    if not encloses_text:
        return None

    if fill_ratio > 0.12:
        return None

    if estimated_thickness > max(int(cfg["thin_component_thickness_px"]) * 2, 1):
        return None

    return {
        "left": component["x0"] + estimated_thickness,
        "right": component["x1"] - estimated_thickness,
        "top": component["y0"] + estimated_thickness,
        "bottom": component["y1"] - estimated_thickness,
    }


def text_like_components(components, bounds_px, cfg):
    min_area = int(cfg["min_foreground_component_px"])
    box_width = max(bounds_px[2] - bounds_px[0], 1)
    box_height = max(bounds_px[3] - bounds_px[1], 1)

    sizable = [component for component in components if component["area"] >= min_area]
    if not sizable:
        sizable = components

    text_like = []
    for component in sizable:
        if not is_horizontal_line(component, box_width, cfg) and not is_vertical_line(
            component, box_height, cfg
        ):
            text_like.append(component)

    return text_like or sizable


def overlap_len(a0, a1, b0, b1):
    return max(0, min(a1, b1) - max(a0, b0))


def rects_intersect(bounds_a, bounds_b):
    return not (
        bounds_a[2] <= bounds_b[0]
        or bounds_b[2] <= bounds_a[0]
        or bounds_a[3] <= bounds_b[1]
        or bounds_b[3] <= bounds_a[1]
    )


def expand_bounds(bounds, margin, img):
    x0, y0, x1, y1 = bounds
    return (
        max(x0 - margin, 0),
        max(y0 - margin, 0),
        min(x1 + margin, img.width),
        min(y1 + margin, img.height),
    )


def clamp_rect_to_boundaries(bounds, boundaries):
    x0, y0, x1, y1 = bounds
    margin = boundaries["margin"]
    if boundaries["left"] is not None:
        x0 = max(x0, boundaries["left"] + margin)
    if boundaries["right"] is not None:
        x1 = min(x1, boundaries["right"] - margin)
    if boundaries["top"] is not None:
        y0 = max(y0, boundaries["top"] + margin)
    if boundaries["bottom"] is not None:
        y1 = min(y1, boundaries["bottom"] - margin)
    return (x0, y0, x1, y1)


def detect_line_boundaries(img: Image.Image, tb: TextBox, bg_rgb255, selected, cfg):
    search_pad = max(int(cfg["line_boundary_search_px"]), 0)
    if search_pad <= 0 or not selected:
        return {
            "left": None,
            "right": None,
            "top": None,
            "bottom": None,
            "margin": 0,
        }

    text_bounds = (
        min(component["x0"] for component in selected),
        min(component["y0"] for component in selected),
        max(component["x1"] for component in selected),
        max(component["y1"] for component in selected),
    )
    search_bounds = (
        max(text_bounds[0] - search_pad, 0),
        max(text_bounds[1] - search_pad, 0),
        min(text_bounds[2] + search_pad, img.width),
        min(text_bounds[3] + search_pad, img.height),
    )
    search_components = foreground_components(img, search_bounds, bg_rgb255, cfg)
    ref_width = max(search_bounds[2] - search_bounds[0], 1)
    ref_height = max(search_bounds[3] - search_bounds[1], 1)

    left = right = top = bottom = None
    for component in search_components:
        x_overlap = overlap_len(
            component["x0"], component["x1"], text_bounds[0], text_bounds[2]
        )
        y_overlap = overlap_len(
            component["y0"], component["y1"], text_bounds[1], text_bounds[3]
        )

        frame_edges = frame_inner_edges(component, text_bounds, cfg)
        if frame_edges is not None:
            left = max(left or frame_edges["left"], frame_edges["left"])
            right = min(right or frame_edges["right"], frame_edges["right"])
            top = max(top or frame_edges["top"], frame_edges["top"])
            bottom = min(bottom or frame_edges["bottom"], frame_edges["bottom"])
            continue

        if is_vertical_line(component, ref_height, cfg) and y_overlap > 0:
            if component["x1"] <= text_bounds[0]:
                left = max(left or component["x1"], component["x1"])
            elif component["x0"] >= text_bounds[2]:
                right = min(right or component["x0"], component["x0"])

        if is_horizontal_line(component, ref_width, cfg) and x_overlap > 0:
            if component["y1"] <= text_bounds[1]:
                top = max(top or component["y1"], component["y1"])
            elif component["y0"] >= text_bounds[3]:
                bottom = min(bottom or component["y0"], component["y0"])

    return {
        "left": left,
        "right": right,
        "top": top,
        "bottom": bottom,
        "margin": max(int(cfg["line_boundary_margin_px"]), 0),
    }


def merge_boundaries(primary, secondary):
    merged = {
        "left": primary.get("left"),
        "right": primary.get("right"),
        "top": primary.get("top"),
        "bottom": primary.get("bottom"),
        "margin": max(primary.get("margin", 0), secondary.get("margin", 0)),
    }
    for side in ("left", "top"):
        if merged[side] is None:
            merged[side] = secondary.get(side)
    for side in ("right", "bottom"):
        if merged[side] is None:
            merged[side] = secondary.get(side)
    return merged


def merge_component_bounds(bounds_list):
    merged = []
    for x0, y0, x1, y1 in sorted(bounds_list):
        merged_index = None
        for index, (mx0, my0, mx1, my1) in enumerate(merged):
            overlaps = not (x1 < mx0 or mx1 < x0 or y1 < my0 or my1 < y0)
            if overlaps:
                merged_index = index
                break

        if merged_index is None:
            merged.append((x0, y0, x1, y1))
        else:
            mx0, my0, mx1, my1 = merged[merged_index]
            merged[merged_index] = (
                min(mx0, x0),
                min(my0, y0),
                max(mx1, x1),
                max(my1, y1),
            )

    return merged


def char_overlapping_components(selected, tb: TextBox, img: Image.Image, cfg):
    if not tb.char_bboxes:
        return selected

    margin = max(int(cfg["char_box_margin_px"]), 0)
    ratio = float(cfg["char_probe_shrink_ratio"])
    char_bounds = [
        expand_bounds(
            pt_box_to_px_bounds(shrink_box(box, ratio), cfg["dpi"], img), margin, img
        )
        for box in tb.char_bboxes
    ]

    matched = []
    for component in selected:
        component_bounds = (
            component["x0"],
            component["y0"],
            component["x1"],
            component["y1"],
        )
        if any(rects_intersect(component_bounds, char_bound) for char_bound in char_bounds):
            matched.append(component)

    return matched


def tight_redaction_rects(img: Image.Image, tb: TextBox, bg_rgb255, cfg, page_boundaries=None):
    bounds_px = pt_box_to_px_bounds(tb.bbox, cfg["dpi"], img)
    components = foreground_components(img, bounds_px, bg_rgb255, cfg)
    if not components:
        return [fitz.Rect(tb.bbox)]

    selected = text_like_components(components, bounds_px, cfg)
    selected = char_overlapping_components(selected, tb, img, cfg)
    if not selected:
        fallback_bounds = [
            expand_bounds(bounds, max(int(cfg["tight_box_padding_px"]), 0), img)
            for bounds in pt_boxes_to_px_bounds(tb.char_bboxes, cfg["dpi"], img)
        ]
        if not fallback_bounds:
            return [fitz.Rect(tb.bbox)]
        boundaries = page_boundaries or {
            "left": None,
            "right": None,
            "top": None,
            "bottom": None,
            "margin": 0,
        }
        clamped_bounds = []
        for bounds in merge_component_bounds(fallback_bounds):
            clamped = clamp_rect_to_boundaries(bounds, boundaries)
            if clamped[0] < clamped[2] and clamped[1] < clamped[3]:
                clamped_bounds.append(clamped)
        if not clamped_bounds:
            return [fitz.Rect(tb.bbox)]
        return [
            px_bounds_to_pt_rect(bounds, cfg["dpi"]) for bounds in clamped_bounds
        ]

    boundaries = page_boundaries or {
        "left": None,
        "right": None,
        "top": None,
        "bottom": None,
        "margin": 0,
    }
    if None in (boundaries["left"], boundaries["right"], boundaries["top"], boundaries["bottom"]):
        local_boundaries = detect_line_boundaries(img, tb, bg_rgb255, selected, cfg)
        boundaries = merge_boundaries(boundaries, local_boundaries)
    pad = max(int(cfg["tight_box_padding_px"]), 0)
    bounds_list = []
    for component in selected:
        bounds = clamp_rect_to_boundaries(
            (
                max(component["x0"] - pad, 0),
                max(component["y0"] - pad, 0),
                min(component["x1"] + pad, img.width),
                min(component["y1"] + pad, img.height),
            ),
            boundaries,
        )
        if bounds[0] < bounds[2] and bounds[1] < bounds[3]:
            bounds_list.append(bounds)

    if not bounds_list:
        return [fitz.Rect(tb.bbox)]

    return [
        px_bounds_to_pt_rect(bounds, cfg["dpi"])
        for bounds in merge_component_bounds(bounds_list)
    ]


def process_page(page, cfg):
    textboxes = extract_textboxes(page, cfg)
    pix = page.get_pixmap(dpi=cfg["dpi"], alpha=False)
    img = Image.open(io.BytesIO(pix.tobytes())).convert("RGB")
    fill_color = parse_fill_color(cfg["fill_color"])
    page_lines = extract_page_vector_lines(page, cfg)
    page_frames = find_frames_from_vector_lines(page_lines, cfg)
    page_geometry = {"lines": page_lines, "frames": page_frames}

    # 覆盖背景矩形
    for tb in textboxes:
        bg_color, bg_rgb255 = dominant_background_color(img, tb.bbox, cfg)
        page_boundaries = page_boundaries_for_text(tb, page_geometry, cfg)
        for erase_rect in tight_redaction_rects(
            img, tb, bg_rgb255, cfg, page_boundaries=page_boundaries
        ):
            page.add_redact_annot(erase_rect, fill=bg_color)

    if textboxes:
        page.apply_redactions()
        removed_blocks = strip_whitespace_only_type3_blocks(page.parent, page)
        if removed_blocks:
            logging.info(
                "Page %d removed %d whitespace-only Type3 text blocks",
                page.number + 1,
                removed_blocks,
            )

    # 重绘文字
    for tb in textboxes:
        fontname, fontfile = resolve_font(tb.font, cfg, tb.text)
        fontsize = tb.size if cfg["font_size"] is None else cfg["font_size"]
        page.insert_text(
            tb.origin,
            tb.text,
            fontfile=fontfile,
            fontname=fontname,
            fontsize=fontsize,
            color=fill_color,
            rotate=tb.rotation,
        )

    logging.info(
        "Page %d processed (%d textboxes, %d vector frames)",
        page.number + 1,
        len(textboxes),
        len(page_frames),
    )


def main():
    parser = argparse.ArgumentParser(description="PDF text replace tool")
    parser.add_argument("-i", "--input", required=True, help="Input PDF file")
    parser.add_argument("-o", "--output", default="output.pdf", help="Output PDF file")
    parser.add_argument("-c", "--config", help="Path to config.yaml")
    parser.add_argument("--dpi", type=int, help="Override DPI setting")
    args = parser.parse_args()

    cfg = load_config(Path(args.config) if args.config else None)
    if args.dpi:
        cfg["dpi"] = args.dpi

    pdf_in = Path(args.input)
    if not pdf_in.exists():
        logging.error("Input file not found: %s", pdf_in)
        sys.exit(1)

    doc = fitz.open(pdf_in)

    for page in doc:
        process_page(page, cfg)

    doc.save(args.output, deflate=True, incremental=False, clean=True, garbage=4)
    logging.info("Saved output to %s", args.output)


if __name__ == "__main__":
    main()
